# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.1
#


# pull base image
FROM ubuntu:16.04

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

RUN apt-get install -y ansible

ENV PLAYBOOK test.yml
RUN ansible-playbook-wrapper



#
# test phase
#

CMD ["java", "-version"]
